export const MODULE_KEYS = [
  "panel_super_admin",
  "dashboard_overview",
  "dashboard_tickets",
  "dashboard_visitas",
  "calendario",
  "visitas",
  "tickets",
  "edificios",
  "equipos_criticos",
  "proyectos",
  "conciliacion_bancaria",
  "cierre_mensual",
  "ingresos",
  "egresos",
  "consumos_recurrentes",
  "historial_pagos",
  "consulta_operacional",
  "verificacion_ggcc",
  "mantenedores",
  "ejecutivos",
  "admin_usuarios",
  "reportes_visitas",
  "reportes_tickets",
  "reportes_financiero",
  "reportes_equipos",
  "reportes_ejecutivos",
  "reportes_egresos",
  "estado_documental",
  "ver_costos",
  "aprobar_equipos",
  "monitoreo_chat_ia",
] as const;

export type ModuleKey = typeof MODULE_KEYS[number];

export interface ModuleDefinition {
  label: string;
  group: string;
  routes: string[];
}

export const MODULE_DEFINITIONS: Record<ModuleKey, ModuleDefinition> = {
  panel_super_admin: { label: "Panel Super Admin", group: "Administración", routes: ["/super-admin"] },
  dashboard_overview: { label: "Dashboard Overview", group: "Dashboards", routes: ["/dashboard/overview"] },
  dashboard_tickets: { label: "Dashboard Tickets Semáforo", group: "Dashboards", routes: ["/dashboard/tickets"] },
  dashboard_visitas: { label: "Dashboard Visitas", group: "Dashboards", routes: ["/dashboard/visitas"] },
  calendario: { label: "Calendario", group: "Operaciones", routes: ["/calendario"] },
  visitas: { label: "Visitas", group: "Operaciones", routes: ["/visitas", "/visitas/programar"] },
  tickets: { label: "Tickets", group: "Operaciones", routes: ["/tickets", "/tickets/nuevo"] },
  edificios: { label: "Edificios", group: "Consulta", routes: ["/edificios"] },
  equipos_criticos: { label: "Equipos Críticos", group: "Consulta", routes: ["/equipos"] },
  proyectos: { label: "Proyectos", group: "Proyectos", routes: ["/proyectos", "/proyectos/semaforo", "/proyectos/calendario"] },
  conciliacion_bancaria: { label: "Conciliación Bancaria", group: "Finanzas", routes: ["/conciliacion-bancaria"] },
  cierre_mensual: { label: "Cierre Mensual", group: "Finanzas", routes: ["/cierre-mensual"] },
  ingresos: { label: "Ingresos", group: "Finanzas", routes: ["/ingresos"] },
  egresos: { label: "Egresos", group: "Finanzas", routes: ["/egresos"] },
  consumos_recurrentes: { label: "Consumos Recurrentes", group: "Finanzas", routes: ["/consumos-recurrentes"] },
  historial_pagos: { label: "Historial de Pagos", group: "Finanzas", routes: ["/historial-pagos"] },
  consulta_operacional: { label: "Consulta Operacional", group: "Operaciones", routes: ["/consulta-operacional"] },
  verificacion_ggcc: { label: "Verificación GGCC", group: "Finanzas", routes: ["/verificacion-ggcc"] },
  mantenedores: { label: "Proveedores", group: "Gestión", routes: ["/mantenedores"] },
  ejecutivos: { label: "Ejecutivos", group: "Gestión", routes: ["/ejecutivos"] },
  admin_usuarios: { label: "Admin Usuarios", group: "Administración", routes: ["/admin/usuarios"] },
  reportes_visitas: { label: "Reporte Visitas", group: "Reportes", routes: ["/reportes/visitas"] },
  reportes_tickets: { label: "Reporte Tickets", group: "Reportes", routes: ["/reportes/tickets"] },
  reportes_financiero: { label: "Reporte Financiero", group: "Reportes", routes: ["/reportes/financiero"] },
  reportes_equipos: { label: "Reporte Equipos", group: "Reportes", routes: ["/reportes/equipos"] },
  reportes_ejecutivos: { label: "Reporte Ejecutivos", group: "Reportes", routes: ["/reportes/ejecutivos"] },
  reportes_egresos: { label: "Reporte Egresos", group: "Reportes", routes: ["/reportes/egresos"] },
  estado_documental: { label: "Estado Documental y Operativo", group: "Reportes", routes: ["/reportes/cumplimiento"] },
  ver_costos: { label: "Ver costos", group: "Permisos Especiales", routes: [] },
  aprobar_equipos: { label: "Aprobar equipos", group: "Permisos Especiales", routes: [] },
  monitoreo_chat_ia: { label: "Monitoreo Chat IA", group: "Administración", routes: ["/monitoreo-chat"] },
};

export type RoleModulePermissions = Record<ModuleKey, boolean>;

export interface RolePermissionsConfig {
  role: string;
  modules: RoleModulePermissions;
  homeRoute: string;
  buildingScope: "all" | "assigned";
}

export const ROLE_LABELS: Record<string, string> = {
  super_admin: "Super Admin",
  gerente_general: "Gerente General",
  gerente_operaciones: "Gerente Operaciones",
  gerente_comercial: "Gerente Comercial",
  gerente_finanzas: "Ejecutivo de Apoyo",
  ejecutivo_operaciones: "Ejecutivo Operaciones",
  conserjeria: "Conserjería",
};

export const ALL_ROLES = [
  "super_admin",
  "gerente_general",
  "gerente_operaciones",
  "gerente_comercial",
  "gerente_finanzas",
  "ejecutivo_operaciones",
  "conserjeria",
] as const;

export const DEFAULT_PERMISSIONS: Record<string, RolePermissionsConfig> = {
  super_admin: {
    role: "super_admin",
    homeRoute: "/super-admin",
    buildingScope: "all",
    modules: {
      panel_super_admin: true,
      dashboard_overview: false,
      dashboard_tickets: false,
      dashboard_visitas: false,
      calendario: false,
      visitas: false,
      tickets: false,
      edificios: false,
      equipos_criticos: false,
      proyectos: true,
      conciliacion_bancaria: false,
      cierre_mensual: false,
      ingresos: false,
      egresos: false,
      consumos_recurrentes: false,
      historial_pagos: false,
      consulta_operacional: false,
      verificacion_ggcc: true,
      mantenedores: false,
      ejecutivos: false,
      admin_usuarios: false,
      reportes_visitas: false,
      reportes_tickets: false,
      reportes_financiero: false,
      reportes_equipos: false,
      reportes_ejecutivos: false,
      reportes_egresos: false,
      estado_documental: false,
      ver_costos: true,
      aprobar_equipos: true,
      monitoreo_chat_ia: true,
    },
  },
  gerente_general: {
    role: "gerente_general",
    homeRoute: "/dashboard/overview",
    buildingScope: "all",
    modules: {
      panel_super_admin: false,
      dashboard_overview: true,
      dashboard_tickets: true,
      dashboard_visitas: true,
      calendario: true,
      visitas: true,
      tickets: true,
      edificios: true,
      equipos_criticos: true,
      proyectos: true,
      conciliacion_bancaria: true,
      cierre_mensual: true,
      ingresos: true,
      egresos: true,
      consumos_recurrentes: true,
      historial_pagos: true,
      consulta_operacional: true,
      verificacion_ggcc: true,
      mantenedores: true,
      ejecutivos: true,
      admin_usuarios: true,
      reportes_visitas: true,
      reportes_tickets: true,
      reportes_financiero: true,
      reportes_equipos: true,
      reportes_ejecutivos: true,
      reportes_egresos: true,
      estado_documental: true,
      ver_costos: true,
      aprobar_equipos: true,
      monitoreo_chat_ia: true,
    },
  },
  gerente_operaciones: {
    role: "gerente_operaciones",
    homeRoute: "/dashboard/tickets",
    buildingScope: "all",
    modules: {
      panel_super_admin: false,
      dashboard_overview: false,
      dashboard_tickets: true,
      dashboard_visitas: true,
      calendario: true,
      visitas: true,
      tickets: true,
      edificios: true,
      equipos_criticos: true,
      proyectos: true,
      conciliacion_bancaria: false,
      cierre_mensual: false,
      ingresos: false,
      egresos: false,
      consumos_recurrentes: false,
      historial_pagos: false,
      consulta_operacional: true,
      verificacion_ggcc: true,
      mantenedores: true,
      ejecutivos: true,
      admin_usuarios: false,
      reportes_visitas: true,
      reportes_tickets: true,
      reportes_financiero: false,
      reportes_equipos: true,
      reportes_ejecutivos: true,
      reportes_egresos: false,
      estado_documental: true,
      ver_costos: true,
      aprobar_equipos: true,
      monitoreo_chat_ia: false,
    },
  },
  gerente_comercial: {
    role: "gerente_comercial",
    homeRoute: "/dashboard/tickets",
    buildingScope: "all",
    modules: {
      panel_super_admin: false,
      dashboard_overview: false,
      dashboard_tickets: true,
      dashboard_visitas: true,
      calendario: true,
      visitas: true,
      tickets: true,
      edificios: true,
      equipos_criticos: true,
      proyectos: true,
      conciliacion_bancaria: true,
      cierre_mensual: true,
      ingresos: true,
      egresos: true,
      consumos_recurrentes: true,
      historial_pagos: true,
      consulta_operacional: false,
      verificacion_ggcc: true,
      mantenedores: true,
      ejecutivos: true,
      admin_usuarios: false,
      reportes_visitas: true,
      reportes_tickets: true,
      reportes_financiero: true,
      reportes_equipos: true,
      reportes_ejecutivos: true,
      reportes_egresos: true,
      estado_documental: true,
      ver_costos: true,
      aprobar_equipos: true,
      monitoreo_chat_ia: false,
    },
  },
  gerente_finanzas: {
    role: "gerente_finanzas",
    homeRoute: "/dashboard/tickets",
    buildingScope: "all",
    modules: {
      panel_super_admin: false,
      dashboard_overview: false,
      dashboard_tickets: true,
      dashboard_visitas: false,
      calendario: false,
      visitas: false,
      tickets: true,
      edificios: false,
      equipos_criticos: false,
      proyectos: false,
      conciliacion_bancaria: true,
      cierre_mensual: true,
      ingresos: true,
      egresos: true,
      consumos_recurrentes: true,
      historial_pagos: true,
      consulta_operacional: false,
      verificacion_ggcc: true,
      mantenedores: false,
      ejecutivos: false,
      admin_usuarios: false,
      reportes_visitas: false,
      reportes_tickets: false,
      reportes_financiero: false,
      reportes_equipos: false,
      reportes_ejecutivos: false,
      reportes_egresos: true,
      estado_documental: true,
      ver_costos: true,
      aprobar_equipos: false,
      monitoreo_chat_ia: false,
    },
  },
  ejecutivo_operaciones: {
    role: "ejecutivo_operaciones",
    homeRoute: "/visitas?view=today",
    buildingScope: "assigned",
    modules: {
      panel_super_admin: false,
      dashboard_overview: false,
      dashboard_tickets: false,
      dashboard_visitas: false,
      calendario: true,
      visitas: true,
      tickets: true,
      edificios: true,
      equipos_criticos: true,
      proyectos: true,
      conciliacion_bancaria: false,
      cierre_mensual: false,
      ingresos: false,
      egresos: false,
      consumos_recurrentes: false,
      historial_pagos: true,
      consulta_operacional: true,
      verificacion_ggcc: true,
      mantenedores: false,
      ejecutivos: false,
      admin_usuarios: false,
      reportes_visitas: false,
      reportes_tickets: false,
      reportes_financiero: false,
      reportes_equipos: false,
      reportes_ejecutivos: false,
      reportes_egresos: false,
      estado_documental: true,
      ver_costos: false,
      aprobar_equipos: false,
      monitoreo_chat_ia: false,
    },
  },
  conserjeria: {
    role: "conserjeria",
    homeRoute: "/tickets",
    buildingScope: "assigned",
    modules: {
      panel_super_admin: false,
      dashboard_overview: false,
      dashboard_tickets: false,
      dashboard_visitas: false,
      calendario: false,
      visitas: false,
      tickets: true,
      edificios: false,
      equipos_criticos: false,
      proyectos: false,
      conciliacion_bancaria: false,
      cierre_mensual: false,
      ingresos: false,
      egresos: true,
      consumos_recurrentes: false,
      historial_pagos: false,
      consulta_operacional: false,
      verificacion_ggcc: false,
      mantenedores: false,
      ejecutivos: false,
      admin_usuarios: false,
      reportes_visitas: false,
      reportes_tickets: false,
      reportes_financiero: false,
      reportes_equipos: false,
      reportes_ejecutivos: false,
      reportes_egresos: false,
      estado_documental: false,
      ver_costos: false,
      aprobar_equipos: false,
      monitoreo_chat_ia: false,
    },
  },
};
